// Import
import { StyleSheet } from 'react-native';

// Component
export const styles = StyleSheet.create({
    headerRibbon: {
        position: 'absolute',
        top: 5,
        right: 5,
        padding: 5,
        width: '10%',
        height: '17%',
        opacity: .618,
        borderRadius: 5,
        backgroundColor: '#fed90f',
        elevation: 5,
    },
    land_headerRibbon: {
        position: 'absolute',
        top: 5,
        right: undefined,
        padding: 5,
        width: '15%',
        height: '10%',
        opacity: .618,
        borderRadius: 5,
        backgroundColor: '#fed90f',
        elevation: 5,
    },
    dark_headerRibbon: {
        backgroundColor: '#001020',
    },
    logsignButton: {
        position: 'absolute',
        top: '5%',
        left: '5%',
        height: 27,
        width: 36,
        backgroundColor: 'transparent',
    },
    land_logsignButton: {
        position: 'absolute',
        top: '15%',
        left: '2%',
        height: 27,
        width: 36,
        backgroundColor: 'transparent',
    },
    profImage: {
        width: '100%',
        height: '100%',
    },
    profImage_psngr: {
        position: 'absolute',
        alignSelf: 'center',
        width: '97%',
        height: '105%',
        resizeMode: 'stretch',
        top: -2,
    },
    profImage_drvr: {
        position: 'absolute',
        alignSelf: 'center',
        width: '80%',
        height: '100%',
        resizeMode: 'stretch',
        top: -2,
    },
    themeSwitch: {
        position: 'absolute',
        top: '56%',
        left: '20%',
        height: 27,
        width: 27,
    },
    land_themeSwitch: {
        position: 'absolute',
        top: '17%',
        left: '62%',
        height: 27,
        width: 27,
    },
    themeImage: {
        width: '100%',
        height: '100%',
    },
    gpsButton: {
        position: 'absolute',
        top: '31%',
        left: '25%',
        height: 25,
        width: 25,
        backgroundColor: 'transparent',
    },
    land_gpsButton: {
        position: 'absolute',
        top: '19%',
        left: '35%',
        height: 25,
        width: 25,
        backgroundColor: 'transparent',
    },
    gpsImage: {
        width: '100%',
        height: '100%',
    },
    infoButton: {
        position: 'absolute',
        top: '83%',
        left: '30%',
        height: 25,
        width: 25,
        backgroundColor: 'transparent',
    },
    land_infoButton: {
        position: 'absolute',
        top: '25%',
        left: '87%',
        height: 25,
        width: 25,
        backgroundColor: 'transparent',
    },
    infoImage: {
        width: '90%',
        height: '90%',
    },
});